@SmartTourism_HostAddress = https://localhost:7148

 POST {{SmartTourism_HostAddress}}/api/geo/get-places
Content-Type: application/json

{
  "categories": [
    "Accommodation","Activity","Natural","Leisure"
  ],
  "filter": {
    "longitude": 26.240300448673793,
    "latitude": 50.6225296,
    "radiusInMeters": 5000
  },
  "bias": {
    "longitude": 26.240300448673793,
    "latitude": 50.6225296
  },
  "limit": 10
}
###

GET {{SmartTourism_HostAddress}}/api/geo/get-neighbors
Content-Type: application/json

###


 POST {{SmartTourism_HostAddress}}/api/geo/get-neighbors-edges-new
Content-Type: application/json

{
  "categories": [
    "Accommodation","Activity","Natural","Leisure", "Catering"
  ],
  "filter": {
    "longitude": 26.240300448673793,
    "latitude": 50.6225296,
    "radiusInMeters": 5000
  },
  "bias": {
    "longitude": 26.240300448673793,
    "latitude": 50.6225296
  },
  "limit": 12
}
